Gitpod support + QoL/Workflow-Verbesserungen in Visual Studio Code
DSczyrba/Vorlage-Latex pull request #60
Opened 2021-06-15 14:58 UTC by jemand771

^-^

* Jeden branch/commit in gitpod öffnen indem man `gitpod.io/#` vor die url schreibt.
* LaTeX Workshop-Integration (native builds deaktiviert, aber pdf-viewer an existierenden build-prozess angebunden)
* Mehr Build-Optionen in VSCode (clean, build+refresh, ...)
* Hübsche buttons in der statusbar:
![image](https://user-images.githubusercontent.com/19669567/122075492-68480300-cdfa-11eb-8245-13ea5220280c.png)
Los geht's von link nach rechts beim Zahnrad, der rest ist VSCode default bzw. irgendwelcher anderer spass.
* Zahnrad: Docker-Build
* Chemie-Dings: Docker-Build, Viewer neu laden
* Leere Datei: Build-Ordner löschen
* PDF-Datei (erkennt man bisschen schlecht): PDF-Viewer starten (geht leider nur, wenn man eine .tex-Datei offen+im Fokus hat)
* Neulade-Pfeil-Kreis: Viewer neu laden

Noch ideen für mehr tasks/buttons? #59 mach ich hier explizit nicht, da muss ich erstmal noch sehen, inwiefern das überhaupt möglich ist.

2021-06-15 15:02 UTC, jemand771 commented
Interessant ist hier auch noch, dass PR-Beschreibungen automatisch um einen gitpod-button erweitert werden können, siehe z.B. https://github.com/jemand771/Vorlage-Latex/pull/13 (den button hab ich da nicht hin getan, das war ein bot)

Um das zu aktivieren müsste @DSczyrba den gitpod-bot zum repo hinzufügen ([anleitung](https://www.gitpod.io/docs/prebuilds/#on-github)), die nötige config ist schon mit eingecheckt. Wenn wir das nicht wollen, würde ich die config trotzdem drin lassen - dann kann man das auf seinem privaten repos einfach mit einem klick aktivieren. (Ganz egal, wie viel sinn das dort macht)
- wie seht ihr das?  Ich bin dafür; das erleichtert späteres änderungen-Testen an der vorlage ungemein, ohne dass man potenziell seinen lokalen workspace zerschiesst.

2021-06-15 15:03 UTC, jemand771 commented
Der PDF-Viewer ist gerade auch noch mildly kaputt (geht in gitpod überhaupt nicht), siehe https://github.com/gitpod-io/gitpod/issues/4513 - vielleicht bastel ich da noch einen workaround für, mal sehen wie schnell die antworten ^^

2021-06-15 15:06 UTC, jemand771 commented on .vscode/tasks.json
> +            "problemMatcher": [],
wenn das diff hier komisch aussieht schieb ich's auf autoformat

2021-06-16 05:41 UTC, TheColin21 commented
> 
> 
> Interessant ist hier auch noch, dass PR-Beschreibungen automatisch um einen gitpod-button erweitert werden können, siehe z.B. [jemand771#13](https://github.com/jemand771/Vorlage-Latex/pull/13) (den button hab ich da nicht hin getan, das war ein bot)
> 
> Um das zu aktivieren müsste @DSczyrba den gitpod-bot zum repo hinzufügen ([anleitung](https://www.gitpod.io/docs/prebuilds/#on-github)), die nötige config ist schon mit eingecheckt. Wenn wir das nicht wollen, würde ich die config trotzdem drin lassen - dann kann man das auf seinem privaten repos einfach mit einem klick aktivieren. (Ganz egal, wie viel sinn das dort macht)
> 
>     * wie seht ihr das?  Ich bin dafür; das erleichtert späteres änderungen-Testen an der vorlage ungemein, ohne dass man potenziell seinen lokalen workspace zerschiesst.

würde ich aktivieren

2021-06-16 05:52 UTC, DSczyrba commented
Gefällt mir alles ganz gut, aber ich finde die Buttons nicht so sexy unten...
Also die Icons, das ist komisch...

Mit dem Text alias (Build, View etc.) wäre man da glaub ich besser gekommen :D

Das andere würde ich aktivieren... :)

2021-06-16 06:01 UTC, TheColin21 commented
> 
> 
> Gefällt mir alles ganz gut, aber ich finde die Buttons nicht so sexy unten...
> Also die Icons, das ist komisch...
> 
> Mit dem Text alias (Build, View etc.) wäre man da glaub ich besser gekommen :D
> 
> Das andere würde ich aktivieren... :)

Ich würde höchstens den Text zusätzlich ranschreiben, ich schreib da mal was rein

2021-06-16 06:12 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(gear)",
`"text": "$(gear)",` --> `"text": "$(gear) Build",`

2021-06-16 06:12 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(beaker) Build",
`"text": "$(beaker) Build",` --> `"text": "$(beaker) Build&Refresh",`

2021-06-16 06:13 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(file)",
`"text": "$(file)",` --> `"text": "$(file) Clean",`

2021-06-16 06:13 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(file-pdf)",
`"text": "$(file-pdf)",` --> `"text": "$(file-pdf) View",`

2021-06-16 06:14 UTC, TheColin21 requested changes
s. Comments an settings.json

2021-06-16 06:14 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(refresh)",
`"text": "$(refresh)",` --> `"text": "$(refresh) Refresh",`

2021-06-16 06:14 UTC, TheColin21 commented on .vscode/settings.json
> +        {
ganzen Block mit zu Build und Build&Refresh schieben (sinnvollere Reihenfolge)

2021-06-16 06:17 UTC, TheColin21 requested changes
jetzt aber

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(gear)",
`"text": "$(gear)",` --> `"text": "$(gear) Build",`

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(beaker) Build",
`"text": "$(beaker) Build",` --> `"text": "$(beaker) Build&Refresh",`

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(file-pdf)",
`"text": "$(file-pdf)",` --> `"text": "$(file-pdf) View",`

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(file)",
`"text": "$(file)",` --> `"text": "$(file) Clean",`

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +        {
ganzen Block mit zu Build und Build&Refresh schieben (sinnvollere Reihenfolge)

2021-06-16 06:17 UTC, TheColin21 commented on .vscode/settings.json
> +            "text": "$(refresh)",
`"text": "$(refresh)",` --> `"text": "$(refresh) Refresh",`

2021-06-16 06:18 UTC, TheColin21 commented
> 
> 
> s. Comments an settings.json

how to delete some shit that you submitted to early

2021-06-16 07:11 UTC, TheColin21 approved these changes
noice

2021-06-16 07:35 UTC, merged